apiVersion: v1
kind: Service
metadata:
  name: pricepred-app-service
spec:
  selector:
    app: pricepred-app
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 5000  # The port your Flask app is running on inside the container
  type: LoadBalancer  # Exposes the service externally with a public IP